------------------------ MODULE CloudflareTrace ------------------------
(***************************************************************************)
(* Trace Validation Specification for Cloudflare Config                   *)
(* This module validates traces generated by the Java implementation       *)
(***************************************************************************)

EXTENDS TLC, Sequences, SequencesExt, Naturals, FiniteSets, Bags, Json, IOUtils, CloudflareConfig, TVOperators, TraceSpec

(* Override CONSTANTS *)

TraceNil == "null"

(* Extract Node set from config *)
TraceNode ==
    ToSet(Config[1].Node)

(* Extract CP name from config *)
TraceCP ==
    Config[2].CP[1]

(* Default values for variables *)
CFDefault(varName) ==
    CASE varName = "cpState" -> "idle"
    []  varName = "cpVersion" -> InitConfig
    []  varName = "nodeConfig" -> [n \in Node |-> InitConfig]
    []  varName = "nodeState" -> [n \in Node |-> "running"]
    []  varName = "deployedNodes" -> {}
    []  varName = "msgs" -> {}
    []  varName = "rolloutCount" -> 0
    []  varName = "trafficBlocked" -> FALSE

(* Update variables from trace - keep unchanged if not in trace *)
CFUpdateVariables(t) ==
    /\ IF "cpState" \in DOMAIN t
       THEN cpState' = ApplyUpdates(cpState, "cpState", t["cpState"])
       ELSE cpState' = cpState
    /\ IF "cpVersion" \in DOMAIN t
       THEN cpVersion' = ApplyUpdates(cpVersion, "cpVersion", t["cpVersion"])
       ELSE cpVersion' = cpVersion
    /\ IF "nodeConfig" \in DOMAIN t
       THEN nodeConfig' = ApplyUpdates(nodeConfig, "nodeConfig", t["nodeConfig"])
       ELSE nodeConfig' = nodeConfig
    /\ IF "nodeState" \in DOMAIN t
       THEN nodeState' = ApplyUpdates(nodeState, "nodeState", t["nodeState"])
       ELSE nodeState' = nodeState
    /\ IF "deployedNodes" \in DOMAIN t
       THEN deployedNodes' = ApplyUpdates(deployedNodes, "deployedNodes", t["deployedNodes"])
       ELSE deployedNodes' = deployedNodes
    /\ IF "msgs" \in DOMAIN t
       THEN msgs' = ApplyUpdates(msgs, "msgs", t["msgs"])
       ELSE msgs' = msgs
    /\ IF "rolloutCount" \in DOMAIN t
       THEN rolloutCount' = ApplyUpdates(rolloutCount, "rolloutCount", t["rolloutCount"])
       ELSE rolloutCount' = rolloutCount
    /\ IF "trafficBlocked" \in DOMAIN t
       THEN trafficBlocked' = ApplyUpdates(trafficBlocked, "trafficBlocked", t["trafficBlocked"])
       ELSE trafficBlocked' = trafficBlocked

(* Predicate actions *)
(* Helper to match event with or without node ID suffix *)
IsEventPrefix(prefix) ==
    /\ l \in 1..Len(Trace)
    /\ "event" \in DOMAIN logline
    /\ \/ logline.event = prefix
       \/ \E n \in Node : logline.event = prefix \o "_" \o n
    /\ l' = l + 1
    /\ CFUpdateVariables(logline)

(* Relaxed predicates - match trace events without full pre/post conditions *)
IsCPStartRollout ==
    IsEvent("CPStartRollout")

IsCPInitiateRollback ==
    IsEvent("CPInitiateRollback")

IsCPFinishDeployment ==
    IsEvent("CPFinishDeployment")

IsNodeReceiveDeploy ==
    IsEventPrefix("NodeReceiveDeploy")

IsNodeCompleteUpdate ==
    IsEventPrefix("NodeCompleteUpdate")

IsNodeFailUpdate ==
    IsEventPrefix("NodeFailUpdate")

IsNodeReceiveRollback ==
    IsEventPrefix("NodeReceiveRollback")

IsGlobalConfigFailure ==
    IsEvent("GlobalConfigFailure")

IsControlPlaneBlocked ==
    IsEvent("ControlPlaneBlocked")

IsReceivedAck ==
    IsEvent("ReceivedAck")

IsRollbackComplete ==
    IsEvent("RollbackComplete")

IsShutdown ==
    IsEventPrefix("shutdown")

(* Trace next state *)
CFTraceNext ==
    \/ IsCPStartRollout
    \/ IsCPInitiateRollback
    \/ IsCPFinishDeployment
    \/ IsNodeReceiveDeploy
    \/ IsNodeCompleteUpdate
    \/ IsNodeFailUpdate
    \/ IsNodeReceiveRollback
    \/ IsGlobalConfigFailure
    \/ IsControlPlaneBlocked
    \/ IsReceivedAck
    \/ IsRollbackComplete
    \/ IsShutdown

(* Base specification *)
BaseSpec == Init /\ [][CFTraceNext]_vars
-----------------------------------------------------------------------------
=============================================================================
